
    # render.yaml
static_sites:
  - name: voting-app-frontend
    build_command: npm run build
    publish_dir: dist
    routes:
      - path: /*
        static_headers:
          - key: Content-Type
            value: text/html